### ISSUE TITLE
com.github.sviperll.meta.Visitor has RunTime retention

### ISSUE THREAD

**Issue by talios** [sviperll/chicory#1]
After updating our OSGi based application to use the new ADT4j 1.0 I discovered I needed to embed/export the `metachicory` package due to `com.github.sviperll.meta.Visitor` having runtime retention. Is this required or can it be relaxed and new versions of both be released?

None of the ADT4j's generated code uses the annotation, but I'm not sure if its used at runtime for any other projects...

**Comment by sviperll** [comment]
Frankly, I've never used (or, more precisely, developed for) OSGi. How severe is the problem? The idea was to provide generic annotation that can be used for different purposes by any package. That's why the most flexible Runtime retention is used. Direct analog is Java 8's [FunctionalInterface annotation](http://docs.oracle.com/javase/8/docs/api/java/lang/FunctionalInterface.html).

I'm not sure about this issue... Can you explain what pain it causes to you more thoroughly?

**Comment by talios** [comment]
How severe - well, at its simplest it actually stopped the application from starting. This was initially resolved by embedding/shipping the jar into our distribution, which isn't so bad since the jar isn't that big, however it does mean it's a contract change in ADT4j ( sure, major version 1.0 change means we should expect that, but previously there were no runtime deps ).

The "pain" is caused by the fact that OSGi ( and soon, Jigsaw in Java 9 ) tracks runtime dependencies at...  well runtime. Since the `@Visitior` annotation is now retained at runtime in our classes, the OSGi metadata tools picked that up as a contract.

The `FunctionalInterface` works as being runtime since it's shipped as part of the JDK and thus is always available.

It might pay to document on the ADT4j site/changelog the GAV of the metachictory package, and that this is now an actual runtime dependency. One of the good things about ADT4j in the first place was its zero runtime dependency.

**Comment by sviperll** [comment]
Well, I understand.

Here are my thoughts on the issue. There are several decisions that can be made.

### Compile-time vs. runtime retention

First of all. We can get rid of this issue entirely and change `@Visitor` annotation retention to compile-time. I don't think that it's a good decision.

Run-time retention potentially has it's uses. For example, we can implement accept-method through reflection, in the similar way like a dependency-injection framework does constructor invocations.

We can discover compelling use-case later. We will be forced to
- either introduce another annotation, which can potentially lead to fragmentation;
- or change `@Visitor`-retention to runtime, which will break all software that uses `@Visitor`.

It's much better to break software sooner (now :) than later!

### Runtime dependency

Following just the same logic it seems better to have some runtime-dependency now than to introduce it later. Some unforeseen feature can demand some run-time dependency!

Can you tolerate some runtime-dependency for ADT4J? What is you criteria for tolerating it?

Metachicory package is designed to be small and controlled by me. If it become too big, I will be able to spawn another package, say metachicory-support, to contain more code. Are you ok with such a contract?

**Comment by talios** [comment]
Well currently it seems the ADT4j update ( and this discussion should probably more be on that project. maybe ) decided to use the `@Visitor` from this common package and introduced the runtime dependency ( which granted, doesn't really affect anyone not using OSGi or one of the other module systems that track that ), and that there are several work arounds ( ship the jar, which isn't actually used by anything and is more an annoyance, ignore the package via OSGi meta data ).

When I say it's more of an annoyance, its that other code-gen libraries such as Immutables.org, or Google Autovalue strive to _not_ have any runtime dependencies, which was also one of the good selling points of using ADT4j, which now has a runtime dependency, for something it doesn't actually need at runtime ( like I said, this should probably be moved to the ADT4j project ).

**Comment by sviperll** [comment]
OK, lets fix it.

Final points
- It's better not to piss off your only users;
- It's better to be better than Immutables.org or Google Autovalue;
- `@Visitor` has little sense in run-time since it relies on information about type-variables  and no type variables' information is present at runtime (a. k. a. erasure :)

**Comment by talios** [comment]
+1 Sorry if I sounded grumpy over this :)
